### ISSUE TITLE
Is this a port from the AspNet.Identity.MySQL

### ISSUE THREAD

**Issue by kwokhou** [danellos/AspNet.Identity.PostgreSQL#1]
Hi there, 

I was looking for custom identity provider for PostgreSQL and found your repo, so I just wanted to know if this is a port from the [AspNet.Identity.MySQL](https://aspnet.codeplex.com/SourceControl/latest#Samples/Identity/AspNet.Identity.MySQL/) project on codeplex.

**Comment by danellos** [comment]
It is a port from [this repo](https://github.com/raquelsa/AspNet.Identity.MySQLL) which appears to be identical to the one on CodePlex. I apparently forgot to link that in the Readme, and will do so now.

I needed my own pgSQL identity provider for a side project that I later abandoned, and the only other viable solutions were paid solutions, so I adapted this MySQL one linked above. I put it up in case anyone else would find it useful.

**Comment by kwokhou** [comment]
Thanks for clarifying. I find this useful.

-----Original Message-----
