### ISSUE TITLE
SQL Bug in UserRolesTable.FindByUserId

### ISSUE THREAD

**Issue by smithygreg** [danellos/AspNet.Identity.PostgreSQL#3]
The SQL code to get the roles for the user is broken.  There is a TODO in there to fix it.
Here is code that will fix it.

`string commandText = "SELECT \"Name\"" +
                                " FROM \"AspNetRoles\" " +
                                " INNER JOIN \"AspNetUserRoles\" ON \"AspNetUserRoles\".\"RoleId\" = \"AspNetRoles\".\"Id\" " +
                                " where \"UserId\" = @userId";`

**Comment by danellos** [comment]
Hi,

Thanks for providing a fix for this! I've added this code into the repo. As I am not able to test this today, I've marked it as a "possible" fix and left the TODO in comments.
